<?php
/**
 * Define WGBH-specific content
 */

/**
 * Implement hook_theme_registry_alter
 */
function wgbh_branding_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'wgbh_branding');
  
  // Get template files in the module path
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  
  // Iterate over any template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
  
    //If the template hasn't been overriden, alter the theme path
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
